const UserSchema = {
  BodyUserTransactionSchema: {
    plan_id: "John Doe",
    price: 19.99,
  },
  BodyUserMovieLikeSchema: {
    movie_id: "65f2a1b2c3d4e5f6a7b8c9d0",
    episode_id: "65f2a1b2c3d4e5f6a7b8c9d1",
    movie_name: "Inception",
    guest_id: "65f2a1b2c3d4e5f6a7b8c9d2",
    status_like: "like", // "like", "dislike", atau "none"
    is_guest: true,
    location_raw: {
      continent: "Asia",
      continentCode: "AS",
      country: "Indonesia",
      countryCode: "ID",
      region: "JK",
      regionName: "Jakarta",
      city: "North Jakarta",
      zip: "14350",
      lat: -6.1474,
      lon: 106.8711,
      timezone: "Asia/Jakarta",
      offset: 25200,
      mobile: false,
      proxy: false,
      hosting: false,
    },
  },
  BodyUserWatchMovieSchema: {
    movie_id: "65f2a1b2c3d4e5f6a7b8c9d0",
    episode_id: "65f2a1b2c3d4e5f6a7b8c9d1",
    guest_id: "65f2a1b2c3d4e5f6a7b8c9d2",
    progress_seconds: 3600, // Detik yang sudah ditonton
    duration_seconds: 7200, // Total durasi movie dalam detik
    is_guest: true,
    location_raw: {
      continent: "Asia",
      continentCode: "AS",
      country: "Indonesia",
      countryCode: "ID",
      region: "JK",
      regionName: "Jakarta",
      city: "North Jakarta",
      zip: "14350",
      lat: -6.1474,
      lon: 106.8711,
      timezone: "Asia/Jakarta",
      offset: 25200,
      mobile: false,
      proxy: false,
      hosting: false,
    },
  },
  BodyUserRatingMovieSchema: {
    movie_id: "65f2a1b2c3d4e5f6a7b8c9d0",
    episode_id: "65f2a1b2c3d4e5f6a7b8c9d1",
    guest_id: "65f2a1b2c3d4e5f6a7b8c9d2",
    is_guest: true,
    rating: 4.5, // Skala 0-5},
    location_raw: {
      continent: "Asia",
      continentCode: "AS",
      country: "Indonesia",
      countryCode: "ID",
      region: "JK",
      regionName: "Jakarta",
      city: "North Jakarta",
      zip: "14350",
      lat: -6.1474,
      lon: 106.8711,
      timezone: "Asia/Jakarta",
      offset: 25200,
      mobile: false,
      proxy: false,
      hosting: false,
    },
  },

  // FOR USER / IAM
  BodyUserIAMSchema: {
    role_id: "",
    username: "john doe",
    email: "john.doe@gmail.com",
    password: "123456",
  },
};

module.exports = UserSchema;
